
CREATE TABLE pitchers (
	id INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	player VARCHAR(255) DEFAULT '',
	team VARCHAR(255) DEFAULT '',
	year VARCHAR(255) DEFAULT '',
	appearances INTEGER(10) DEFAULT 0,
	wins INTEGER(10) DEFAULT 0,
	losses INTEGER(10) DEFAULT 0,
	save INTEGER(10) DEFAULT 0,
	hold INTEGER(10) DEFAULT 0,
	holdpoint INTEGER(10) DEFAULT 0,
	complete_games INTEGER(10) DEFAULT 0,
	shutouts INTEGER(10) DEFAULT 0,
	non_walk INTEGER(10) DEFAULT 0,
	winning_percentage DOUBLE DEFAULT 0,
	batters_faced INTEGER(10) DEFAULT 0,
	innings_pitched INTEGER(10) DEFAULT 0,
	hits INTEGER(10) DEFAULT 0,
	homeruns INTEGER(10) DEFAULT 0,
	bases_on_balls INTEGER(10) DEFAULT 0,
	intentional_walks INTEGER(10) DEFAULT 0,
	hit_by_pitch INTEGER(10) DEFAULT 0,
	strikeouts INTEGER(10) DEFAULT 0,
	wild_pitches INTEGER(10) DEFAULT 0,
	balks INTEGER(10) DEFAULT 0,
	runs INTEGER(10) DEFAULT 0,
	earned_runs INTEGER(10) DEFAULT 0,
	earned_run_average DOUBLE DEFAULT 0,
	created DATETIME DEFAULT null,
	modified DATETIME DEFAULT null,
	PRIMARY KEY  (id)
);

CREATE TABLE batters (
	id INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	player VARCHAR(255) DEFAULT '',
	team VARCHAR(255) DEFAULT '',
	game INTEGER(10) DEFAULT 0,
	plate_appearance INTEGER(10) DEFAULT 0,
	at_bats INTEGER(10) DEFAULT 0,
	run_score INTEGER(10) DEFAULT 0,
	hits INTEGER(10) DEFAULT 0,
	base2 INTEGER(10) DEFAULT 0,
	base3 INTEGER(10) DEFAULT 0,
	homeruns INTEGER(10) DEFAULT 0,
	totale_bases INTEGER(10) DEFAULT 0,
	runs_batted_in INTEGER(10) DEFAULT 0,
	stolen_bases INTEGER(10) DEFAULT 0,
	caught_stealling INTEGER(10) DEFAULT 0,
	sacrifice_hits INTEGER(10) DEFAULT 0,
	sacrifice_flies INTEGER(10) DEFAULT 0,
	bases_on_balls INTEGER(10) DEFAULT 0,
	intentional_walks INTEGER(10) DEFAULT 0,
	hit_by_pitch INTEGER(10) DEFAULT 0,
	strikeouts INTEGER(10) DEFAULT 0,
	double_plays INTEGER(10) DEFAULT 0,
	batting_average DOUBLE DEFAULT 0,
	slugging_percentage DOUBLE DEFAULT 0,
	on_base_percentage DOUBLE DEFAULT 0,
	created DATETIME DEFAULT null,
	modified DATETIME DEFAULT null,
	PRIMARY KEY  (id)
);

CREATE TABLE defences (
	id INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	player VARCHAR(255) DEFAULT '',
	team VARCHAR(255) DEFAULT '',
	games INTEGER(10) DEFAULT 0,
	put_outs INTEGER(10) DEFAULT 0,
	assists INTEGER(10) DEFAULT 0,
	errors INTEGER(10) DEFAULT 0,
	double_plays INTEGER(10) DEFAULT 0,
	passed_balls INTEGER(10) DEFAULT 0,
	fielding_average DOUBLE DEFAULT 0,
	created DATETIME DEFAULT null,
	modified DATETIME DEFAULT null,
	PRIMARY KEY  (id)
);
